# Generated by Django 3.0 on 2021-06-01 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessorieProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=10)),
                ('for_kid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('thumnail', models.ImageField(upload_to='upload/products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('black_quantity', models.IntegerField(default=0)),
                ('red_quantity', models.IntegerField(default=0)),
                ('grey_quantity', models.IntegerField(default=0)),
                ('product_options', models.CharField(choices=[('Scarf', 'Scarf'), ('Hat', 'Hat'), ('Glove', 'Glove'), ('Glasse', 'Glasse'), ('Jewelry', 'Jewelry'), ('Bag', 'Bag')], max_length=255)),
            ],
            options={
                'verbose_name': 'Accessorie Product',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cosmetics', 'Cosmetics'), ('Accessories', 'Accessories'), ('Clothes', 'Clothes')], max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ClotheProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=10)),
                ('for_kid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('thumnail', models.ImageField(upload_to='upload/products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('black_quantity', models.IntegerField(default=0)),
                ('red_quantity', models.IntegerField(default=0)),
                ('grey_quantity', models.IntegerField(default=0)),
                ('size', models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('XS-S', 'XS-S'), ('S', 'S'), ('M-L', 'M-L'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=255, null=True)),
                ('product_options', models.CharField(choices=[('Jacket', 'Jacket'), ('Coat', 'Coat'), ('Dresse', 'Dresse'), ('Shirt', 'Shirt'), ('T-shirt', 'T-shirt'), ('Jean', 'Jean')], max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('related_product', models.ManyToManyField(blank=True, default=None, related_name='_clotheproduct_related_product_+', to='core.ClotheProduct')),
            ],
            options={
                'verbose_name': 'Clothes Product',
            },
        ),
        migrations.CreateModel(
            name='CosmeticProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=10)),
                ('for_kid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('thumnail', models.ImageField(upload_to='upload/products')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product_options', models.CharField(choices=[('Perfume', 'Perfume'), ('Depilatory', 'Depilatory'), ('Cream', 'Cream'), ('Soap', 'Soap'), ('Face Powder', 'Face Powder')], max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('related_product', models.ManyToManyField(blank=True, default=None, related_name='_cosmeticproduct_related_product_+', to='core.CosmeticProduct')),
            ],
            options={
                'verbose_name': 'Cosmetic Product',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('acrie_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AccessorieProduct')),
                ('clothe_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ClotheProduct')),
                ('costic_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CosmeticProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Customer')),
                ('products', models.ManyToManyField(to='core.OrderProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload/products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClotheProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.CharField(max_length=200)),
                ('suite', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('order_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
            ],
        ),
        migrations.AddField(
            model_name='accessorieproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AddField(
            model_name='accessorieproduct',
            name='related_product',
            field=models.ManyToManyField(blank=True, default=None, related_name='_accessorieproduct_related_product_+', to='core.AccessorieProduct'),
        ),
    ]
