# Generated by Django 3.0 on 2021-06-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='acrie_product',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='clothe_product',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='costic_product',
        ),
        migrations.AddField(
            model_name='cosmeticproduct',
            name='black_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cosmeticproduct',
            name='grey_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cosmeticproduct',
            name='red_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
