# Generated by Django 3.0 on 2021-06-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210603_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='session_order',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
