# Generated by Django 3.0 on 2021-06-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_billinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='state',
        ),
    ]
