# Generated by Django 3.0 on 2021-06-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_billinginfo_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
